### ISSUE TITLE
change the tasks.loop seconds

### ISSUE THREAD

**Issue by tescomealdealll** [PythonJoshua/Python-Discord-Bot#1]
change the tasks.loop seconds to something above 60, lower can cause ratelimiting so it isnt a good idea

**Comment by PythonJoshua** [comment]
> change the tasks.loop seconds to something above 60, lower can cause ratelimiting so it isnt a good idea

will fix when i have time, or you can contribute and add it 🙂

**Comment by tescomealdealll** [comment]
i think i did it idk
